install.packages("dbscan")
install.packages("fpc")
library(dbscan)
library(fpc)
data(airquality)
scaled_data <- scale(airquality)
chameleon_clusters <- dbscan(scaled_data, eps = 0.3, minPts = 5)
plot(scaled_data, col = chameleon_clusters$cluster + 1, main = "Chameleon Clustering")
sil_width <- silhouette(chameleon_clusters$cluster, dist(scaled_data))
mean_sil_width <- mean(sil_width[, "sil_width"])
dunn_index <- dunn(d = dist(scaled_data), clusters = chameleon_clusters$cluster)
